// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220930002515_EstoqueId]")]
    partial class EstoqueId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("API.Estoque", b =>
                {
                    b.Property<string>("EstoqueId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProdutoId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeProduto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorProduto")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstoqueId");

                    b.HasIndex("ProdutoId1");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("API.Fornecedor", b =>
                {
                    b.Property<int>("FornecedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CnpjFornecedor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailFornecedor")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFornecedor")
                        .HasColumnType("TEXT");

                    b.HasKey("FornecedorId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("API.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Preco")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("API.Estoque", b =>
                {
                    b.HasOne("API.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId1");

                    b.Navigation("produto");
                });
#pragma warning restore 612, 618
        }
    }
}
