### Listar os estoques
GET https://localhost:5001/api/estoque/list

### Buscar um fornecedor pelo id
GET https://localhost:5001/api/estoque/getbyid/2

### Cadastrar um estoque
POST https://localhost:5001/api/estoque/create
Content-Type: application/json

{
   "EstoqueId" : 133,
   "TipoEstoque" : "info",
    "Produto":{
        "produtoId": 267,
        "tipoEstoque":"info",
        "nome": "mouse gamer",
        "categoria": null,
        "preco": 0,
        "quantidade": 0,
        "fornecedor": "Fornecedor",
        "criadoEm": "2022-10-01T16:17:14.172841"
    }
}

### Deletar um fornecedor / deletar/nome
DELETE https://localhost:5001/api/estoque/delete/Pneu

### Alterar um fornecedor
PUT  https://localhost:5001/api/estoque/update
Content-Type: application/json

{
    "EstoqueId" : 5,
   "TipoEstoque" : "teste",
    "ValorProduto" : 10
  
}